feat: implement reading/writing http-responses via CDP
gemini-testing/hermione-dumps-recorder pull request #2
Opened 2022-10-12 01:40 UTC by KuznetsovRoman

2022-10-12 11:37 UTC, KuznetsovRoman reviewed
## Что сделано

- Реализован основной функционал по перехвату AJAX запросов с помощью CDP.  В качестве ключа запроса все еще берется чистый url со всеми query параметрами

- Дампы можно сохранять в моде create/save в соответствующие папки, и читать в моде play

- dumpsDir принимает либо название папки с дампами, либо коллбэк `(test: Hermione.Test) => string`

2022-10-12 11:37 UTC, KuznetsovRoman commented on src/store.ts
> +    private queryCounter!: Map<string, number>;
- workersRunner: назначается методом consume после create

- dumpPromise: промис на чтение файла с дампом, либо на создание пустого. Инициализируется либо через loadDump (play), либо через init (save, create)

- dump: сам дамп. Перед тем, как начать применять `get`, `set` сначала нужно подождать `Store.resolve()`, это установит дамп, когда файл закончит считываться с файловой системы.

- queryCounter: счетчик запросов по url'у. Инициализируется там же, где и dumpPromise.

2022-10-12 11:37 UTC, KuznetsovRoman commented on src/types.ts
> +    };
```javascript
{
    responses: {
        hashKey1: [responseHash1, responceHash2, responceHash1]
        hashKey2: [responceHash3, responceHash3]
    }
    storage: {
        responceHash1: DumpResponse
        responceHash2: DumpResponse
        responceHash3: DumpResponse
    }
}
```

2022-10-12 11:37 UTC, KuznetsovRoman commented on src/index.ts
> +    };
Это нужно, чтобы дожидаться завершения выполнения последнего запроса на запись. TEST_PASS синхронный, поэтому там только накидываем задачи на запись файла, а ждем их в RUNNER_END

2022-10-12 11:37 UTC, KuznetsovRoman commented on src/config-utils.ts
> +export function arrayStringOption(name: string, defaultValue: string[] | null): Parser<string[] | null> {
Пользователь может дать только массив строк, но `defaultValue == null` - валидно. Это нужно для списка браузеров: таким образом, если пользователь не объявлял список браузеров, перехватчик используется в CDP сессиях, а если объявлял - то только в объявленных браузерах. Профит от такого решения в том, что нет какой то неявной привязки "пустой массив = какие то браузеры"

2022-10-14 13:10 UTC, DudaGod requested changes
Пока до конца не досмотрел. Но уже есть, что исправить. Досмотрю в понедельник.

2022-10-14 13:10 UTC, DudaGod commented on src/index.ts
> +    const config = parseDumpsConfig(opts, hermione.config);
Я бы просто `parseConfig` называл. Понятно, что речь идет о конфиге плагина.

2022-10-14 13:10 UTC, DudaGod commented on src/config.ts
> +export function parseDumpsConfig(pluginOpts: DumpsPluginConfig, hermioneOpts: Hermione.Config): DumpsPluginConfig {
А почему второй параметр называется - `hermioneOpts`? Там же конфиг гермионы, а не опции какие-то.

2022-10-14 13:10 UTC, DudaGod commented on src/config.ts
> +            cliPrefix: "--hermione-dumps-recorder-",
`cliPrefix` должен называться просто `--dumps-recorder`. Ведь странно запускать `hermione` вот так - `npx hermione --hermione-dumps-recorder-mode play`. Итак понятно, что опция для гермионы.

2022-10-14 13:10 UTC, DudaGod commented on src/config.ts
> +import { arrayStringOption, stringOrCallbackOption, booleanOption, runModeOption } from "./config-utils";
А почему бы в `src` не создать папку `config` и не положить туда `index.ts` с самой логикой конфига и просто `utils.ts` с хелперами? Тогда у нас логика связанная с конфигом будет явно отделена от других файлов. Для `flows` и `cdp` ты же отдельную папку создал.

2022-10-14 13:10 UTC, DudaGod commented on src/config.ts
> +            hosts: arrayStringOption("hostsPatterns", [hermioneOpts.baseUrl + "*"]),
У тебя же опция `hosts` называется, а не `hostsPatterns`

2022-10-14 13:10 UTC, DudaGod commented on src/config.ts
> +            browsers: arrayStringOption("browsers", null),
Почему все таки не массив пустой? И может не нужно пытаться за пользователя включить плагин для всех CDP браузеров? Может пусть сам явно указывает в каких браузерах нужно включать такую фичу. Плюс в том, что это будет явно. А минус в том, что менее удобно. Но в большинстве плагинов мы все таки просим пользователя явно указывать такую опцию.

2022-10-14 13:10 UTC, DudaGod commented on src/config.ts
> +    browsers: string[] | null;
предлагаю все таки переделать на явное определение списка браузеров юзером

2022-10-14 13:10 UTC, DudaGod commented on src/config.ts
> +            dumpsDir: stringOrCallbackOption("dumpsDir", "test-dumps"),
Давай по дефолту будет называть - `hermione-dumps`. И предлагаю это название унести в файл с констнтами

2022-10-14 13:10 UTC, DudaGod commented on src/config.ts
> +    const config = parseOptions({ options: pluginOpts, env, argv });
А почему тут сразу `return` не выполнить?
Ну и можно было бы `pluginOpts` просто в `options` переименовать и тут бы тогда чуть красивее было бы.

2022-10-14 13:10 UTC, DudaGod commented on src/config-utils.ts
> +export const booleanOption = (name: string, defaultValue = false): Parser<boolean> =>
А зачем тут `defaultValue` в `false` выставлять? Тут же просто нужно указать `boolean`. А пользователь этой функции сам определит дефолт. Т.е. это функция может применяться не только для опции `enabled`

2022-10-14 13:10 UTC, DudaGod commented on src/config-utils.ts
> +            throw new Error(`Option '${name}' must be a boolean`);
Тут и ниже правильнее было бы кидать `TypeError`. Так как ошибки связаны именно с типом данных, который пользователь указал.

2022-10-14 13:10 UTC, DudaGod commented on src/config-utils.ts
> +            throw new Error(`Option '${name}' must be a boolean`);
У тебя валидация каждой опции очень похожа. Можно немного подрефакторить и набросать такой хелпер - https://github.com/gemini-testing/hermione-storybook/blob/master/src/hermione/config.ts#L5-L11

2022-10-14 13:10 UTC, DudaGod commented on src/config-utils.ts
> +            if (_.isBoolean(val)) {
А зачем так писать? Нам же достаточно проверить, что условие не удовлетворяется и кинуть ошибку. Т.е. нам не нужно из функции `validate` вообще какое либо значение возвращать. Т.е. можно сразу писать `if` с невалидным условием и кидать ошибку.

В функциях `validate` ниже такая же проблема.

2022-10-14 13:10 UTC, DudaGod commented on src/config-utils.ts
> +export const stringOrCallbackOption = (
Так а почему бы не назвать просто `stringOrFunctionOption`?

2022-10-14 13:10 UTC, DudaGod commented on src/config-utils.ts
> +    defaultValue: string | DumpsDirCallback,
У тебя тут не должно быть завязки на `DumpsDirCallback`. Это должна быть просто какая-то функция. Ты же завел общий хелпер, который может использоваться и в другой какой-то опции.

2022-10-14 13:10 UTC, DudaGod commented on src/config-utils.ts
> +            throw new Error(`Option '${name}' must be presented and equal to 'play' | 'save' | 'create'`);
Тут значения `play`, `save` и `create` нужно брать из `RunModes`. И вместо `|` я бы писал `or`.

Ну и `presented` можно выгасить. Очевидно, что если значение должно быть эквивалентно одному из значений `runMode`, то оно не может быть пустым.

2022-10-14 13:10 UTC, DudaGod commented on src/config-utils.ts
> +export function arrayStringOption(name: string, defaultValue: string[] | null): Parser<string[] | null> {
А зачем два одинаковых переопределения с `| null`. Вообще предлагаю пока сделать явное указание списка браузеров.

2022-10-14 13:10 UTC, DudaGod commented on src/config.ts
> +    hosts: string[];
Похоже эту опцию нужно все таки переименовать в `hostsPatterns`. Чтобы пользователь явно понимал, что там должна быть маска. Которая летит в fetch domain - https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#method-enable

2022-10-14 13:10 UTC, DudaGod commented on src/index.ts
> +    const withWritingQueue = async (promise: Promise<void>): Promise<void> => {
С этим есть проблема. Представим, что у нас тесты запускаются в 1 воркере (явно указали в конфиге), ну и мастер у нас есть. При этом машинка на которой выполняются тесты имеет 16 CPU допустим. Далее у нас в хроме параллельно запускается 10 сессий (выставлена опция `sessionPerBrowser = 10`). Получается у нас 10 тестов выполняются параллельно (каждому тесту выделили процессорное время на отдельном ядре). Но мастер у нас один. В итоге у нас в мастере выстраиваются промисы в очередь и обрабатываются строго друг за другому, так как ты явно используешь `then`. Очевидно, что это очень медленно, так как вообще нет никакой необходимости в этой очереди. Можно заюзать библиотеку `p-queue` - https://github.com/sindresorhus/p-queue, которая может выполнять промисы паралллельно в зависимости от количества ядер. Пример использования в `html-reporter` - https://github.com/gemini-testing/html-reporter/blob/1e4693356c90c66cc6224a32ae6ffc82ece3acc4/lib/gui/tool-runner/report-subscriber.js#L14.

А на `RUNNER_END` нужно дожидаться завершения следующим образом - https://github.com/gemini-testing/html-reporter/blob/1e4693356c90c66cc6224a32ae6ffc82ece3acc4/lib/gui/tool-runner/report-subscriber.js#L107.

2022-10-14 13:10 UTC, DudaGod commented on src/config.ts
> +            cliPrefix: "--hermione-dumps-recorder-",
Кажется удобнее было бы просто писать `npx hermione --play` или `npx hermione --save`.
Пример как можно такие опции поднести прямо в вызов гермионы - https://github.com/gemini-testing/hermione-test-repeater/blob/master/lib/index.js#L17-L24.

С другой стороны если плагин будет называться просто `hermione-dumps`. То достаточно указать `npx hermione --dumps-mode play`. И вроде бы такая опция более понятна, чем просто `--play`

2022-10-14 13:10 UTC, DudaGod commented on src/index.ts
> +        await declareModeFlows(
А зачем нам тут эти приставки `flows`? Почему просто не `declareModes`? Я вижу, что ты взял куски кода из `hermione-mock-images`. Но кажется можно чуть проще именовать.

2022-10-14 13:10 UTC, DudaGod commented on src/index.ts
> +                onPlay: async () => loadFlow(session, config.hosts, store),
`loadFlow` я бы переименовал в `playMode`. Т.е. чтобы было соответствие между названием опции и названием обработчика. Ну или `readMode` и `writeMode`.

2022-10-14 13:10 UTC, DudaGod commented on src/index.ts
> +    hermione.on(hermione.events.TEST_BEGIN, test => {
А зачем еще одна подписка на `test_begin`? Почему нельзя все реализовать в предыдущей?

2022-10-14 13:10 UTC, DudaGod commented on src/index.ts
> +        hermione.on(hermione.events.TEST_PASS, () => {
А зачем ты `TEST_PASS` заворачиваешь внутрь `TEST_BEGIN`? В `TEST_PASS` же летит первым аргумент тест, который ты можешь дальше использовать.

Ну и тут же у тебя проблема будет. Ты в итоге на каждый `TEST_BEGIN` вешаешь новый обработчик `TEST_PASS`. Т.е. при запуске 10 тестов у тебя будет 10 обработчиков `TEST_PASS` и каждый из них будет вызываться когда тест пройдет. Т.е. если 10 тестов пройдут в итоге успешно, то у тебя вызовется 100 обработчиков `TEST_PASS`.

2022-10-14 13:10 UTC, DudaGod commented on src/index.ts
> +        declareModeFlows(
А ты же в курсе, что это у тебя асинхронный метод? Тут же получается нет гарантии, что в момент когда в тесте перехватится первый урл и сработает cdp interceptor, то в это время дамп уже будет точно загружен и из него можно будет просто получить данные.

UPD: увидел, что работает похоже за счет явного вызова `store.resolve()` в интерцепторах. Не очень очевидно конечно.

2022-10-14 13:10 UTC, DudaGod commented on src/index.ts
> +                onSave: () => store.init(),
Почему метод `init` называется? Почему не `writeDump` например? По идее название должно быть похоже с методом чтения дампов

2022-10-14 13:10 UTC, DudaGod commented on src/index.ts
> +        if (config.browsers === null && !browser.isDevTools) {
С этим тоже есть проблема. Представим, что у меня есть браузер без поддержки CDP. Ты в итоге для моего браузера выполнишь кучу лишней логики про подписку на события `test_pass`, настройку режима воспроизведения/записи дампов и т.д. Хотя этого всего делать для него не нужно.

Предлагаю, чтобы юзер сам выставлял список браузеров явно.

2022-10-17 08:59 UTC, KuznetsovRoman commented on src/index.ts
> +                onSave: () => store.init(),
`loadDump` на `TEST_BEGIN` в режиме `play` загружает дамп с файловой системы
`store.init` на `TEST_BEGIN` в режимах `save | create` инициализирует в памяти пустой дамп

2022-10-17 10:35 UTC, DudaGod commented on src/index.ts
> +                onSave: () => store.init(),
> store.init на TEST_BEGIN в режимах save | create инициализирует в памяти пустой дамп

Но название `init` довольно абстрактное и кажется, что оно может вызываться в любом режиме для первоначальной инициализации. Может стоит назвать `prepareToSaveDump`? Букв больше, но зато понятно по названию метода, что в нем происходит.

2022-10-17 10:49 UTC, KuznetsovRoman commented on src/index.ts
> +                onSave: () => store.init(),
Может, `createEmptyDump`?

Вообще, можно избавиться от вызва `init`, если выполнять его тело в конструкторе `Store`. Тогда `loadDump` будет просто перезаписывать эти поля.

2022-10-17 12:13 UTC, DudaGod requested changes
Еще не хватает документации и тестов

2022-10-17 12:13 UTC, DudaGod commented on src/declareModeFlows.ts
> +import { RunMode } from "./types";
Почему этот файл у тебя называется в camelCase, а не в kebab-case, как остальные файлы?
Ну и вообще я бы для этой функции не создавал отдельный файл. Почему его просто не утащить в папку `flows` в файл `index.ts`? Ну и еще раз напомню, что я бы `flows` все таки переименовал, так как modes намного больше подходит.

2022-10-17 12:13 UTC, DudaGod commented on src/index.ts
> +        await declareModeFlows(
Я бы просто писал `useMode`

2022-10-17 12:13 UTC, DudaGod commented on src/index.ts
> +    hermione.on(hermione.events.TEST_BEGIN, test => {
Тут к нам тест может приходить, который выполняется в браузере который не определен явно в поле `browsers`, т.е. в этом случае ничего делать не нужно. В `test` есть поле `browserId`. И тут нужно проверять нужно ли вызывать какой-то обработчик или нет.

2022-10-17 12:13 UTC, DudaGod commented on src/index.ts
> +                onCreate: () => store.init(),
А зачем нам вообще тут какой-то `init` вызывать? В нем же происходит просто инициализация двух переменных. Почему это нельзя сделать при первом вызове `gatherFlow`? Только в нем нужен будет матчинг между тестом и браузером.

2022-10-17 12:13 UTC, DudaGod commented on src/index.ts
> +                onPlay: () => store.loadDump(test),
У нас же до http запросов тест может вообще не дойти. Например поднятие сессии может упасть или какие-то `beforeEach` хуки, а мы уже дамп загрузили.

Я бы все таки грузил дамп по требованию. Прилетел запрос - загрузил дамп.

2022-10-17 12:13 UTC, DudaGod commented on src/index.ts
> +    });
Предлагаю на `test_begin` ничего этого не делать. Причины:
- вызовы асинхронных методов которые мы не дожидаемся плохая практика
- в режиме play предзагружаем дампы, хотя не факт, что они будут нужны
- в режиме save/create можно вообще ничего не делать

2022-10-17 12:13 UTC, DudaGod commented on src/index.ts
> +                    onSave: () => withWritingQueue(store.saveDump(test, true)),
Читая вызов `saveDump(test, true)` можно ли сказать, что означает второй параметр `true`? Почему бы не передавать вторым аргумент объект с опциями в виде - `{overwrite: true}`? Ведь так значительно понятнее будет

2022-10-17 12:13 UTC, DudaGod commented on src/index.ts
> +        hermione.on(hermione.events.TEST_PASS, () => {
Тут тоже нужно не забыть добавить логику про проверку, нужно ли что-то выполнять для теста выполненного в таком-то браузере.

2022-10-17 12:13 UTC, DudaGod commented on src/store.ts
> +    public consume(workersRunner: WorkersRunner): void {
А почему этот метод называется `consume`? По названию он не выглядит как обязательный для корректной работы данного класса. Почему бы не назвать его `initialize`? В этом случае будет понятно, что сначала нужно явно проинициализировать `store` и только потом его использовать.

2022-10-17 12:13 UTC, DudaGod commented on src/store.ts
> +    public async resolve(): Promise<void> {
Вот этот метод мне вообще не нравится и я предлагаю от него избавится. Особенно если реализовать чтение дампа по запросу. Т.е. пришел http-запрос который нужно перехватить и дамп еще не прочитан, тогда читаем. Если он уже прочитан, тогда используем уже прочитанный дамп.

2022-10-17 12:13 UTC, DudaGod commented on src/store.ts
> +        const testDirPath = path.dirname(test.file!);
Зачем в `test.file` восклицательный знак? В типах hermione это поле не описано? Если не описано то нужно его просто расширить. Ну или поправить тайпинги в hermione (лучший вариант).

2022-10-17 12:13 UTC, DudaGod commented on src/store.ts
> +        const targetPath = path.relative(cwd, dumpPath);
А зачем ты путь к относительному приводишь, а не работаешь с абсолютным?

2022-10-17 12:13 UTC, DudaGod commented on src/store.ts
> +        const dumpPath = path.resolve(testDirPath, dumpsDir, this.getFileName(test));
В случае если пользователь указал функцию, то ты должен просто докинуть к ней название файла, а не пытаться еще подпихнуть к нему путь к директории от `test.file`. Пример как работает `screenshotsDir` - https://github.com/gemini-testing/hermione/blob/master/lib/config/browser-config.js#L15-L17

2022-10-17 12:13 UTC, DudaGod commented on src/store.ts
> +        const dumpPath = path.resolve(testDirPath, dumpsDir, this.getFileName(test));
Ну и я не вижу расширения файла - `.json`

2022-10-17 12:13 UTC, DudaGod commented on src/store.ts
> +        return createHash("md5").update(`${test.fullTitle()}#${test.browserId}`).digest("hex");
Длину хэша нужно контроллировать и она не должна быть больше какого-то значения. Например в котике у нас хеши длинной 20 символов. И `inputEncoding` нужно `ascii` выставлять явно (или он по дефолту такой?)

2022-10-17 12:13 UTC, DudaGod commented on src/store.ts
> +        const responseString = `${response.body}#${Object.values(response.headers).join("#")}`;
А всякие статус коды, методы (`get`, `post`) и т.д. не летят разве? По идее `statusCode` тоже нужно учитывать.

2022-10-17 12:13 UTC, DudaGod commented on src/types.ts
> +    };
Тут же по факту `hashKey1` - это урл по которому на странице выполняется запрос.
`responseHash` - это хеш от ответа
`DumpResponse` - ответ, который отправим пользователю

Может правильнее было бы `responses` переименовать в `requests`, так как он по сути содержит урлы запросов с матчингом на ответы. А `storage` в `responses`? Может так будет чуть понятнее?

2022-10-17 12:13 UTC, DudaGod commented on src/store.ts
> +        return createHash("md5").update(response.body).update(responseString).digest("hex");
Возможно стоит вынести в хелпер хеширование.

2022-10-17 12:13 UTC, DudaGod commented on src/index.ts
> +    const store = Store.create(config.dumpsDir);
С этим стором есть проблема. Объясню на примере. Пусть параллельно выполняется 2 теста в режиме чтения дампов (дамп для каждого теста существует). Тесты выполняются параллельно. Сначала запустился первый тест и на `TEST_BEGIN` ты считал дамп для него и в сторе сложил его в переменную `dumpPromise`. Затем сразу же начал выполнятся второй тест и ты прочитал дамп и для него и сложил в ту же самую переменную (т.е. мы перетерли `dumpPromise`). После чего в первом тесте срабатывает `interceptor` и мы смотрим на дамп из соседнего теста, а не свой.

2022-10-17 12:13 UTC, DudaGod commented on src/cdp/interceptor.ts
> +        const body = Buffer.from(interceptionResponse.body, interceptionResponse.base64Encoded ? "base64" : "utf8");
Почему здесь получаем только `body`? Почему не смотрим на статус коды, методы отправки (`get`, `post`, ...) и т.д.?

2022-10-17 12:13 UTC, DudaGod commented on src/flows/gatherFlow.ts
> +    await responseInterceptor.enable();
А почему `enable` вызываем после `listen`? Это принципиально или разницы нет? Судя по доке все равно должен дожидаться ответа от перехватчика.

2022-10-17 12:13 UTC, DudaGod commented on src/flows/loadFlow.ts
> +            process.exit(1);
Так нельзя делать. У тебя в итоге один запрос из одного теста, который не получилось считать уронит весь запуск тестов.

2022-10-17 12:13 UTC, DudaGod commented on src/cdp/interceptor.ts
> +            respondWithMock: this.respondWithMock.bind(this),
Почему просто через стрелочную функцию тут не можем указать? (я обычно стараюсь не использовать `bind`-ы если это возможно)

2022-10-17 12:29 UTC, KuznetsovRoman commented on src/index.ts
> +                onCreate: () => store.init(),
Этот инит выполняется перед каждым тестом

Если попробовать выполнять его в вызовах gatherFlow, то дампы прошлых тестов останутся в памяти

2022-10-17 12:44 UTC, KuznetsovRoman commented on src/index.ts
> +                onPlay: () => store.loadDump(test),
Тут сложный вопрос. Выигрыш в реализованном случае - можем подгружать файл, пока запускается браузер и грузится html. Выигрыш в таком случае, если начинать грузить дамп как только пришел запрос - непонятен. Да и тут смотреть надо, как часто падает поднятие сессии и beforeEach хуки. Как будто бы даже если есть какой-то проигрыш в таких случаях, в среднем все равно выгоднее делать так.

2022-10-17 12:56 UTC, KuznetsovRoman commented on src/store.ts
> +        const testDirPath = path.dirname(test.file!);
В типе Hermione.Test не описано, используется родительский Mocha.Runnable в котором это поле имеет тип `string | undefined` (полагаю, `undefined` он если запускать НЕ через CLI)

2022-10-17 14:33 UTC, KuznetsovRoman commented on src/flows/gatherFlow.ts
> +    await responseInterceptor.enable();
> Это принципиально или разницы нет?

Да нет, не принципиально.

2022-10-17 14:37 UTC, KuznetsovRoman commented on src/cdp/interceptor.ts
> +        const body = Buffer.from(interceptionResponse.body, interceptionResponse.base64Encoded ? "base64" : "utf8");
> Почему здесь получаем только `body`?

Потому что Fetch.getResponseBody дает только его.

> Почему не смотрим на статус коды, методы отправки, итд

А зачем? Добавил статус коды в дампы, но они берутся в другом месте, из `listen`

2022-10-18 07:31 UTC, KuznetsovRoman commented on src/config-utils.ts
> +    defaultValue: string | DumpsDirCallback,
Если использовать просто `Function` - typescript eslint ругается. Использовать (arg: any) => string или отключить это правило?

2022-10-24 12:38 UTC, KuznetsovRoman commented on src/config.ts
> +            dumpsDir: stringOrCallbackOption("dumpsDir", "test-dumps"),
В файле будет только одна константа?

2022-10-24 14:25 UTC, DudaGod commented on src/config-utils.ts
> +    defaultValue: string | DumpsDirCallback,
А какой текст содержится в его ругательстве?

2022-10-24 14:27 UTC, DudaGod commented on src/config.ts
> +            dumpsDir: stringOrCallbackOption("dumpsDir", "test-dumps"),
Пока да, потом еще что-то добавится.

2022-10-24 14:30 UTC, KuznetsovRoman commented on src/config-utils.ts
> +    defaultValue: string | DumpsDirCallback,
`error  Don't use Function as a type. The Function type accepts any function-like value.
It provides no type safety when calling the function, which can be a common source of bugs.
It also accepts things like class declarations, which will throw at runtime as they will not be called with new.
If you are expecting the function to accept certain arguments, you should explicitly define the function shape  @typescript-eslint/ban-types`

2022-10-24 20:58 UTC, KuznetsovRoman commented on src/index.ts
> +    });
Проблема в том, что нужно в любом случае где-нибудь брать `test`, чтобы понимать, к какому тесту относится каждый запрос. Кажется, что TEST_BEGIN - лучшее место. где можно этот тест брать. 

Если тут в режимах `save`/`create` ничего не делать, то не будут чиститься данные дампа от прошлого теста.

2022-10-24 20:59 UTC, KuznetsovRoman commented on src/store.ts
> +    public consume(workersRunner: WorkersRunner): void {
Избавился от него, перенес в конструктор.

2022-10-27 07:54 UTC, KuznetsovRoman commented
## Как теперь чистятся дампы завершенных сессий из оперативки

После записи дампа.
Упавшие тесты чистят память пораньше, потому что пройденным тестам нужно сначала сохранить дамп.

### Один тест на сессию
<img width="437" alt="Screen Shot 2022-10-26 at 00 02 56" src="https://user-images.githubusercontent.com/54893992/198223477-19607582-80a5-45ca-8d79-164d5bedb921.png">

### Несколько тестов на сессию
<img width="422" alt="Screen Shot 2022-10-26 at 00 07 21" src="https://user-images.githubusercontent.com/54893992/198223836-8f9c536d-cf89-422c-9687-6942f6608ddb.png">

2022-11-01 14:29 UTC, DudaGod reviewed
Посмотрел часть. Есть вопросы. В целом уже сильно лучше.

2022-11-01 14:29 UTC, DudaGod commented on src/config/index.ts
> +            envPrefix: "dumps_",
В `envPrefix` нужно `hermione_` вернуть. Для переменных окружения мы название инструмента явно оставляем. Так как переменные окружения могут указываться в какой-то CI таске или конфиге. И по названию `dumps_` нефига понятно не будет для чего это.

А вот `cli` опции указываются явно при запуске гермионы и относятся непосредственно к ней. Поэтому приставку `hermione` не пишем. Т.е. `cliPrefix` у тебя уже указан верно.

2022-11-01 14:29 UTC, DudaGod commented on src/config/index.ts
> +            hostsPatterns: arrayStringOption("hostsPatterns", [hermioneConfig.baseUrl + "*"]),
Кажется, что опция должна называться все таки `hostPatterns`, т.е. правильно когда только второе слово во множественном числе пишется.

2022-11-01 14:29 UTC, DudaGod commented on src/config/index.ts
> +            enabled: booleanOption("enabled", false),
А напомни почему мы его выключаем по умолчанию? Кажется, что большинство плагинов мы стараемся сразу же включать. Чтобы пользователю меньше опций нужно было указать. Пример - https://github.com/gemini-testing/hermione-storybook/blob/master/src/hermione/config.ts#L39

2022-11-01 14:29 UTC, DudaGod commented on src/config/index.ts
> +export type DumpsPluginConfig = {
А зачем сюда `dumps` зашивать? Можно же просто `PluginConfig` назвать. В итоге когда ты его переименуешь в `hermione-mocks`, то тут ничего править не придется.

2022-11-01 14:29 UTC, DudaGod commented on src/config/index.ts
> +import { DumpsDirCallback, RunMode } from "../types";
А почему не явный `import type`?

2022-11-01 14:29 UTC, DudaGod commented on src/config/utils.ts
> +        parseCli: (val: string) => Boolean(JSON.parse(val)),
А почему тут просто `JSON.parse` не использовать? Ведь `typeof JSON.parse('false') === 'boolean'`

2022-11-01 14:29 UTC, DudaGod commented on src/config/utils.ts
> +        parseCli: JSON.parse,
А что ты тут парсить пытаешься? У тебя же тут всегда строка

2022-11-01 14:29 UTC, DudaGod commented on src/config/utils.ts
> +                .join(" or "),
Давай `validate` опишем как нормальную функцию и результат выполнения этой конструкции сохраним в переменную. Сейчас код читается не очень.

2022-11-01 14:29 UTC, DudaGod commented on src/config/index.ts
> +            mode: runModeOption("mode", RunMode.Save),
А почему `save` дефолтное поведение? Я бы дефолтом выбрал `play`. Т.е. запускаем тесты с чтением дампов. Если нужно сохранить дампы, то пользователь явно должен сообщить об этом.

2022-11-01 14:29 UTC, DudaGod commented on src/config/index.ts
> +            cliPrefix: "--dumps-",
Может сразу все под `mocks` переделаем? Чтобы осталось просто перенести код в репо - `hermione-mocks`?

2022-11-01 14:29 UTC, DudaGod commented on .eslintrc.js
> +        "@typescript-eslint/no-non-null-assertion": "off",
Зачем нам это правило вообще отключать на весь пакет? В infratest вижу, что мы используем только точечно (т.е. через коммент)

2022-11-01 14:29 UTC, DudaGod commented on .eslintrc.js
> +        "@typescript-eslint/ban-types": [
Не понял зачем `Function` банить?
@sipayRT может лучше [Pango](https://dota2.ru/heroes/pangolier/) забаним, ну или [Marci](https://dota2.ru/heroes/pangolier/) хотя бы.

2022-11-01 14:29 UTC, DudaGod commented on src/config/index.ts
> +        }),
Не думал как будет выглядеть конфиг если мы захотим с помощью данного плагина еще и картинки мокать? Т.е. объединить логику с плагином `hermione-mock-images`. Нужно же будет указывать один из ResourceType-ов - https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-ResourceType. Может сразу поддержать возможно указания? Т.е. сейчас плагин будет поддерживать только `XHR`

2022-11-01 14:29 UTC, DudaGod commented on src/config/utils.ts
> +        validate: assertType<string | Function>(name, isStringOrFunction, "string | (test: Hermione.Test) => string"),
А почему просто текстом не писать (я про - `string | (test: Hermione.Test) => string"`)? Т.е. ошибка будет - `dumpsDir must be a string or function, but got number`. Или в твоем варианте `dumpsDir must be a string | (test: Hermione.Test) => string, but got number`. 

Кажется, что писать типы в ошибке не имеет смысла. Он этот тип должен в коде получать при описании плагина. А ошибка должна быть человекочитаемая.

2022-11-01 14:29 UTC, DudaGod commented on src/config/utils.ts
> +        validate: assertType<string[]>(name, isStringArray, "string[]"),
Тут тоже самое про тип.

2022-11-01 14:29 UTC, DudaGod commented on src/index.ts
>      if (!config.enabled || hermione.isWorker()) {
Я бы пустой строкой от парсинга конфига отбил.

2022-11-01 14:29 UTC, DudaGod commented on src/index.ts
> +    hermione.on(hermione.events.RUNNER_START, runner => {
У нас обычно аргументы функции всегда в скобочки заворачиваются, чтобы в будущем можно было быстро добавить еще один аргумент. Но на этом правиле не настаиваю можем обсудить в чате.

2022-11-01 14:29 UTC, DudaGod commented on src/index.ts
>      hermione.on(hermione.events.SESSION_START, async (browser, info) => {
Я бы из `info` сразу же доставал с помощью деструктуризации необходимые поля. Т.е. писал бы так - `{browserId, sessionId}`

2022-11-01 14:29 UTC, DudaGod commented on src/index.ts
> +                onPlay: () => stores.get(test.sessionId)!.loadDump(test),
Кажется я уже об этом писал, но напишу еще раз. Зачем нам загружать тут дамп? Почему мы его не загружаем при первом запросе? Т.е. внутри `attachTarget`. Код тогда получится чуть проще и не придется заводить какой-то `dumpPromise` внутри `store` и ждать его.

По производительности должно быть тоже самое.

2022-11-01 14:29 UTC, DudaGod commented on src/index.ts
> +                onCreate: () => stores.get(test.sessionId)!.createEmptyDump(),
Ну и про эти методы тоже самое

2022-11-01 14:29 UTC, DudaGod commented on src/index.ts
> +                onSave: cleanStaleStores,
Что-то я не понял. Зачем нам на `test_fail` что-то чистить? Почему нельзя почистить просто `session_end`?

2022-11-01 14:29 UTC, DudaGod commented on src/index.ts
> +                onSave: () => onWrite(sessionId),
Зачем нам вообще какой-то `sessionEndedIds`? У нас при завершении сессии уже есть `id`. Вот его можно и почистить тут.

2022-11-01 14:29 UTC, DudaGod commented on src/index.ts
> +    const cleanStaleStores = (): void => sessionEndedIds.forEach(id => sessionEndedIds.delete(id) && stores.delete(id) && console.log(`deleted ${id}`));
Остался `console.log`. Ну и не пойму зачем удалять вообще `sessionEndedIds`. Можно же просто удалять один конкретный стор на `session_end`

2022-11-01 14:29 UTC, DudaGod commented on src/index.ts
> +        useModes(
Что-то я не понял, а почему не удаляем стор, который использовался при чтении дампа? Ведь у нас куча инфы в памяти останется если много тестов запустить.

2022-11-01 23:02 UTC, KuznetsovRoman commented on src/config/index.ts
> +            hostsPatterns: arrayStringOption("hostsPatterns", [hermioneConfig.baseUrl + "*"]),
Обсуждаемый вопрос:
 - hostPatterns - шаблоны хоста
 - host**s** patterns - шаблоны хостов
 
 Вот по идее нам нужно именно второе

2022-11-01 23:04 UTC, KuznetsovRoman commented on src/config/index.ts
> +export type DumpsPluginConfig = {
В экспортируемых наружу типах хотел быть конкретнее: мало ли кто снаружи заимпортитует этот тип из пакета

Исправлю

2022-11-01 23:18 UTC, KuznetsovRoman commented on src/config/index.ts
> +import { DumpsDirCallback, RunMode } from "../types";
Потому что `RunMode` не совсем тип:

```ts
// src/types.ts

1    export enum RunMode {
2        Play = "play",
3        Save = "save",
4        Create = "create",
5    }
```

- *Почему он enum?*
  - Потому что у `enum` можно взять `Object.values()` чтоб в рантайме проверить пользовательский ввод на соответствие типу

2022-11-01 23:19 UTC, KuznetsovRoman commented on src/config/utils.ts
> +        parseCli: (val: string) => Boolean(JSON.parse(val)),
Позаимствовал эту часть кода, думал, так надо

Исправил

2022-11-01 23:21 UTC, KuznetsovRoman commented on src/config/utils.ts
> +        parseCli: JSON.parse,
Не посмотрел значение по умолчанию у `configparser`'a

Исправил

2022-11-01 23:24 UTC, KuznetsovRoman commented on src/config/utils.ts
> +        parseCli: JSON.parse,
Так теряется возможность говорить пользователю, что он ввел, допустим, объект вместо строки, но да, невелика потеря

Исправил

2022-11-02 10:08 UTC, KuznetsovRoman commented on .eslintrc.js
> +        "@typescript-eslint/ban-types": [
Это разбан Function. 
```ts
        "@typescript-eslint/ban-types": [
            "error",
            {
                types: {
                    Function: false
                }
            }
        ],
```

Мы так выключаем его ругань на `Function`

2022-11-02 10:56 UTC, KuznetsovRoman commented on src/config/index.ts
> +        }),
Думал, но для этого недостаточно просто добавить в список перехватываемых ResourceType'ов еще и картинки. Скорее всего, под это надо будет в конфиге заводить какое-то поле, являющееся объектом/массивом, и в нем уже указывать, какой именно функционал от плагина нужен, потом в самом плагине как-то уже обрабатывать это. Например, можно будет поменять `useMode` чтобы он еще и массив фичей принимал, а там уже выполнял что дали при текущих `mode` для всех `features`

2022-11-02 11:07 UTC, KuznetsovRoman commented on src/index.ts
> +    hermione.on(hermione.events.RUNNER_START, runner => {
Завернул везде, где такое возможно.

Конструкции типа 
```ts 
sessionEndedIds.forEach(id => sessionEndedIds.delete(id) && stores.delete(id));
```
не трогал, потому что там скобки сделают код менее читабельным, а второй аргумент туда в 99% случаев никто добавлять не захочет

2022-11-02 11:16 UTC, KuznetsovRoman commented on src/index.ts
> +                onPlay: () => stores.get(test.sessionId)!.loadDump(test),
> По производительности должно быть тоже самое

Да, так и есть

> Кажется я уже об этом писал

Да, а я на это уже отвечал:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/54893992/199475555-0cc17f44-5c85-4e8e-8a63-fdd5a33ac85d.png">

> Почему мы его не загружаем при первом запросе? Т.е. внутри `attachTarget`?

Потому что `attachTarget` аттачит интерсептор на начале каждой сессии, и там нельзя взять инстанс `Hermione.Test`, так как таких тестов в одной сессии много выполняется

2022-11-02 11:24 UTC, KuznetsovRoman commented on src/index.ts
> +                onCreate: () => stores.get(test.sessionId)!.createEmptyDump(),
Тут, опять же, тестов в одной сессии обычно больше одного, и вот такое `createEmptyDump`, перезаписывая `Store.dumpPromise` удаляет дампы из прошлого теста. Без этого - дамп каждого следующего теста хранил бы также дамп от предыдущего. А дамп от предыдущего - дамп от пред-предыдущего, и так до начала сессии

2022-11-02 11:30 UTC, KuznetsovRoman commented on src/index.ts
> +                onSave: () => onWrite(sessionId),
> Зачем нам вообще какой-то sessionEndedIds? У нас при завершении сессии уже есть id. Вот его можно и почистить тут.

Нельзя. Для последней сессии сначала срабатывает `SESSION_END`, а уже потом `TEST_END`. В таком случае в `SESSION_END` мы почистим дамп, который еще не записался. Поэтому в очередь кладем промисы вида: "*Запиши дамп, потом прибери в `stores` за собой*", чтобы удостовериться, что все дампы, которые мы чистим, уже записаны на файловую систему.

2022-11-02 11:37 UTC, KuznetsovRoman commented on src/index.ts
> +    const cleanStaleStores = (): void => sessionEndedIds.forEach(id => sessionEndedIds.delete(id) && stores.delete(id) && console.log(`deleted ${id}`));
> Не пойму, зачем удалять вообще `sessionEndedIds`. Можно же просто удалять один конкретный стор на `session_end`

Нельзя. На эвенте `SESSION_END` мы не знаем, заканчивает ли этот тест сессию. То есть, если это последняя сессия, то там `SESSION_END` триггерится раньше. Если не последняя - то сначала `TEST_END`. Получается, что мы:
- Не знаем, можно ли удалить эту сессию, находясь внутри `TEST_END` (либо "Да" (последняя сессия), либо "Не знаю")
- Не знаем, можно ли удалить эту сессию, находясь внутри `SESSION_END` (либо "Наверное"(не последняя сессия), либо "Нет")

2022-11-02 11:49 UTC, DudaGod commented on src/index.ts
> +                onPlay: () => stores.get(test.sessionId)!.loadDump(test),
> Потому что attachTarget аттачит интерсептор на начале каждой сессии, и там нельзя взять инстанс Hermione.Test, так как таких тестов в одной сессии много выполняется

Так мы же уже договаривались, что нам нужна просто мапка с соответствием `sessionId` к `test`. В один момент времени в сессии выполняется только один тест. В итоге из этой мапки по `sessionId` достаем текущий тест и используем его в `attachTarget`. За счет этого никакая асинхронная логика внутри синхронного события не вызывается. И нет всяких `dumpPromise`-ов, которые нужно не забывать дождаться.

2022-11-02 11:52 UTC, closed without merging

2022-11-02 11:56 UTC, DudaGod commented on src/config/index.ts
> +            hostsPatterns: arrayStringOption("hostsPatterns", [hermioneConfig.baseUrl + "*"]),
Я точно помню, что в данном случае правильно писать `host patterns`, но не могу найти правило.

@xrsd нужна помощь эксперта в английском языке.

2022-11-02 12:01 UTC, DudaGod commented on src/config/index.ts
> +import { DumpsDirCallback, RunMode } from "../types";
Ну тогда `enum` нужно отдельно импортить. А тип `DumpsDirCallback` отдельно с помощью `import type`. Почему нужно использовать `import type` - https://stackoverflow.com/questions/61412000/do-i-need-to-use-the-import-type-feature-of-typescript-3-8-if-all-of-my-import

2022-11-02 12:07 UTC, DudaGod commented on .eslintrc.js
> +        "@typescript-eslint/ban-types": [
А мы разве не можем не использовать `Function`? Он же скорей всего не случайно ругается. Видимо хочет, чтобы были описаны аргументы и возвращаемое значение. Т.е. можно явно вместо `Function` юзнуть запись вида `type fn = (...) => ...`

2022-11-02 12:18 UTC, DudaGod commented on src/config/index.ts
> +        }),
> Думал, но для этого недостаточно просто добавить в список перехватываемых ResourceType'ов еще и картинки

Да, это понятно. Картинки нужно обрабатывать по другому. Я тут предлагал сразу структуру продумать, чтобы последующие типы легко было добавлять. Тот же websocket нужен будет скорей всего.

Мне кажется было бы удобно вот так конфиг описывать:
```
plugins: {
  'hermione-mocks': {
    enabled: true,
    'XHR': {
        hostPatterns: '...',
        dumpsDir: 'dumps1',
        browsers: ['b1', 'b2'],
        mode: 'play'
    },
    'Stylesheet|Script': {
        hostPatterns: '...',
        dumpsDir: 'dumps2',
        browsers: ['b3'],
        mode: 'play'
    },
  }
}
```

2022-11-02 12:21 UTC, xrsd commented on src/config/index.ts
> +            hostsPatterns: arrayStringOption("hostsPatterns", [hermioneConfig.baseUrl + "*"]),
Димон, ты путаешь кейс с `count`: `student count`, `host count` – там мн. число не пишется.

А Рома выше все правильно написал: если речь про шаблоны хостов, то оба слова во мн. числе пишутся, а если про шаблоны одного хоста – то первое слово тогда будет в ед. числе.

2022-11-02 12:34 UTC, DudaGod commented on src/index.ts
> +                onCreate: () => stores.get(test.sessionId)!.createEmptyDump(),
> Тут, опять же, тестов в одной сессии обычно больше одного, и вот такое createEmptyDump, перезаписывая Store.dumpPromise удаляет дампы из прошлого теста. Без этого - дамп каждого следующего теста хранил бы также дамп от предыдущего. А дамп от предыдущего - дамп от пред-предыдущего, и так до начала сессии

Тут же зависит как напишешь код. Можно на `save` чистить все что необходимо. А вообще кажется, что правильнее было бы иметь инстанс работы с дампами (сейчас называется `store`) на тест, а не на сессию. Тогда все бы удалялось само собой и думать об этом даже не приходилось бы. По времени думаю никаких просадок не было бы, так как создание этого инстанса должно быть дешевой операцией.

2022-11-02 12:45 UTC, DudaGod commented on src/index.ts
> +                onSave: () => onWrite(sessionId),
Действительно. Неудобно, что об этом думать приходится. Хотелось бы, чтобы js сам прибирал все, что уже не достижимо. Не смотрел на использование `WeakMap`?

2022-11-02 12:46 UTC, DudaGod commented on src/index.ts
> +    const cleanStaleStores = (): void => sessionEndedIds.forEach(id => sessionEndedIds.delete(id) && stores.delete(id) && console.log(`deleted ${id}`));
В таком случае правильно было бы иметь стор на тест (писал про это выше). Тогда такой проблемы не будет же.

2022-11-02 12:47 UTC, KuznetsovRoman commented on .eslintrc.js
> +        "@typescript-eslint/ban-types": [
<img width="816" alt="image" src="https://user-images.githubusercontent.com/54893992/199493377-ff87d919-9951-40bc-9e81-cfa368ea0ef0.png">

2022-11-02 12:54 UTC, KuznetsovRoman commented on src/config/index.ts
> +        }),
Тогда будет непонятно, что из этого относится к дампам, а что - к `hermione-mock-images`
Да и пользователю, кмк, удобнее будет выбрать: "Хочу вот это и вот это", а не выбирать по типу ресурса

`mode` кстати можно вынести: не вижу такого случая, когда пользователю явно понадобится запустить разные фичи в разных режимах (Ну или сделать как с .hermione.conf.js и его browsers, где внутренние параметры перезаписывают внешние, и у внешних есть значение по умолчанию).

2022-11-02 13:03 UTC, KuznetsovRoman commented on src/index.ts
> +                onSave: cleanStaleStores,
Допустим, как минимум последние тесты в каждой сессии падают. Тогда, если мы чистим их только на `TEST_PASS`, `stores` будет постоянно расти, ни разу не очистившись.

> Почему нельзя почистить просто `SESSION_END`?

Обсуждается в других диалогах

2022-11-02 13:16 UTC, DudaGod commented on src/config/index.ts
> +        }),
> Тогда будет непонятно, что из этого относится к дампам, а что - к hermione-mock-images
Да и пользователю, кмк, удобнее будет выбрать: "Хочу чтоб картинки заменялись, и дампы сохранялись", а не выбирать по типу ресурса

Почему не понятно то? Указываешь ключем `Image` и внутри необходимые паттерны, браузеры и папку куда сохранять. А сам плагин подстраивается под указанный тип и знает как его правильно застабать.

> mode кстати можно вынести

Да, можно.

2022-11-02 13:40 UTC, KuznetsovRoman commented on src/index.ts
> +                onPlay: () => stores.get(test.sessionId)!.loadDump(test),
Предлагаешь всю мапку `sessionIdToTest` передавать в `readMode` / `writeMode` внутри `attachTarget`?
Как-то некрасиво получится, что загружаем дампы с файловой системы в `readMode.ts` / `writeMode.ts`, а сохраняем в `index.ts`.

Имхо, даже более некрасиво, чем оставить так: (теперь `Store.get` и  `Store.set` асинхронные и дожидаются этого промиса под капотом)

2022-11-05 23:32 UTC, KuznetsovRoman commented on src/index.ts
> +                onPlay: () => stores.get(test.sessionId)!.loadDump(test),
Сделал немного по-другому: на `TEST_BEGIN` создается новый стор, в `attachTarget` в `readMode` / `writeMode` передаем коллбэк, возвращающий нужный стор.

2022-11-06 00:03 UTC, KuznetsovRoman commented on src/index.ts
> +                onSave: () => onWrite(sessionId),
WeakMap'у нужен объект в качестве ключа. Придется создавать какие-то массивы объектов (по 1 на сессию) и как-то менеджить их. Решил проблему по другому, без этих sessionEndedIds, созданием `Store` на каждый тест. В таком случае в методе стора `saveDump` после сохранения можно обнулять дамп. Итого:

- В режиме чтения дампов на `TEST_END` удаляется инстанс стора по айди сессии, так как все равно создадим новый на `TEST_BEGIN`, если надо будет.
- В режиме записи дампов на `TEST_FAIL` можем сразу удалить стор, а на `TEST_PASS` вызываем `saveDump`, который обнулит дамп после записи. В худшем случае после прогонки теста в `stores` будет *N* пустых `Store`, где *N* - количество сессий.

2022-11-06 00:09 UTC, KuznetsovRoman commented on src/index.ts
> +                onSave: cleanStaleStores,
Потому что `SESSION_END` вызывается раньше, чем `TEST_END` для последней сессии. Обошел эту проблему [вот так](https://github.com/gemini-testing/hermione-dumps-recorder/pull/2#discussion_r1014744758)